version: '3.8'

services:
  vote:
    image: localhost:5000/vote:latest
    build:
      context: .
      dockerfile: vote/Dockerfile
    networks:
      - vote
    ports:
      - "8080:8080"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    depends_on:
      - redis

  worker:
    image: localhost:5000/worker:latest
    build:
      context: .
      dockerfile: worker/Dockerfile
    networks:
      - vote
      - result
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    depends_on:
      - redis
      - postgres

  result:
    image: localhost:5000/result:latest
    build:
      context: .
      dockerfile: result/Dockerfile
    networks:
      - result
    ports:
      - "8888:8888"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres
      - worker

  redis:
    image: redis:latest
    networks:
      - vote
    ports:
      - "6379:6379"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - result
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  vote:
  result:

volumes:
  postgres_data:
